### ISSUE TITLE
msmUnitConversion | Missing value from port new_units

### ISSUE THREAD

**Issue by ranrchen** [ranrchen/CyberWater_Beta#2]
Traceback (most recent call last):
  File "C:\VisTrails\vistrails\core\modules\vistrails_module.py", line 581, in update
    self.compute()
  File "C:\VisTrails\vistrails\packages\msm\vistrails_helpers\preprocess\Operations.py", line 28, in compute
    new_units = self.get_input(self.NEW_UNITS)
  File "C:\VisTrails\vistrails\core\modules\vistrails_module.py", line 1188, in get_input
    raise ModuleError(self, "Missing value from port %s" % port_name)
ModuleError: Missing value from port new_units

**Comment by ranrchen** [comment]
Users need to configure the input port named "new_units" in msmUnitConversion module
