### ISSUE TITLE
TimeRange | Uncaught exception: Exception: Validation failed. Message: min_value must be lower or equal to max_value

### ISSUE THREAD

**Issue by ranrchen** [ranrchen/CyberWater_Beta#4]
Traceback (most recent call last):
  File "C:\VisTrails\vistrails\core\modules\vistrails_module.py", line 581, in update
    self.compute()
  File "C:\VisTrails\vistrails\packages\msm\vistrails_helpers\studycase\TimeRange.py", line 44, in compute
    timeRangeModel = TimeRangeModel.createFromStrings(timeini, timeend, step, subrange)
  File "C:\VisTrails\vistrails\packages\msm\ui_model\TimeRangeModel.py", line 39, in createFromStrings
    timeRange = TimeRangeModel(timeini, timeend, step, subrange)
  File "C:\VisTrails\vistrails\packages\msm\ui_model\RangeModel.py", line 32, in __init__
    [min_value, max_value, step] = self.validate_inputs(min_value, max_value, step)
  File "C:\VisTrails\vistrails\packages\msm\ui_model\TimeRangeModel.py", line 30, in validate_inputs
    Validate.isTrue(self.a_before_b(timeini, timeend), "min_value must be lower or equal to max_value")
  File "C:\VisTrails\vistrails\packages\msm\utils\Validate.py", line 10, in isTrue
    raise Exception("Validation failed. Message: " + msg)
Exception: Validation failed. Message: min_value must be lower or equal to max_value

**Comment by ranrchen** [comment]
For the "TimeRange" module configuration, the value for the parameter of init_time should be strictly less than the one for end_time.
